### ISSUE TITLE
No bundled_pip_dependencies in building container 

### ISSUE THREAD

**Issue by Syphixs** [bentoml/BentoML#1318] opened 2020-12-09 14:18 UTC
**Describe the bug**
ERROR: Invalid requirement: './bundled_pip_dependencies/*'
Hint: It looks like a path. File './bundled_pip_dependencies/*' does not exist.

**To Reproduce**

![image](https://user-images.githubusercontent.com/33832024/101640948-6d825a80-3a31-11eb-9072-b108011c9632.png)

**Environment:**
 - OS: 10.15.7
 - Python Version 3.7.9
 - BentoML Version 0.10

**Comment by cryanzpj** [comment] 2020-12-09 17:01
found same issue in the 0.10.0 version.

**Describe the bug**
docker build failed

**To Reproduce**
`
cd ./20201209113627_677B50
docker build .`

[20201209113627_677B50.zip](https://github.com/bentoml/BentoML/files/5667441/20201209113627_677B50.zip)

**Screenshots/Logs**
Sending build context to Docker daemon  33.28kB
Step 1/15 : FROM bentoml/model-server:0.10.0-py37
0.10.0-py37: Pulling from bentoml/model-server
68ced04f60ab: Already exists
9c388eb6d33c: Already exists
96cf53b3a9dd: Already exists
45f376fce055: Already exists
36f19dc68493: Pull complete
23801c3ff7cc: Pull complete
59545f916689: Pull complete
d7f3546322f9: Pull complete
Digest: sha256:af054adb079feaea8704c20cb52dcdc3cf2e5d5917197d1583e43383b9712539
Status: Downloaded newer image for bentoml/model-server:0.10.0-py37
 ---> 889443e6a36c
Step 2/15 : ARG EXTRA_PIP_INSTALL_ARGS=
 ---> Running in 7c0b0a0c60c7
Removing intermediate container 7c0b0a0c60c7
 ---> f6695b8610fd
Step 3/15 : ENV EXTRA_PIP_INSTALL_ARGS $EXTRA_PIP_INSTALL_ARGS
 ---> Running in f9b8054367e5
Removing intermediate container f9b8054367e5
 ---> 92c2b393891e
Step 4/15 : COPY environment.yml requirements.txt setup.sh* bentoml-init.sh python_version* /bento/
 ---> b6f02a32f2f0
Step 5/15 : WORKDIR /bento
 ---> Running in 631a84af8e40
Removing intermediate container 631a84af8e40
 ---> a009c948b3ef
Step 6/15 : COPY docker-entrypoint.sh /usr/local/bin/
 ---> 761ebb2a2b77
Step 7/15 : COPY environment.yml bundled_pip_dependencies*  /bento/bundled_pip_dependencies/
 ---> 7c418a38a2cc
Step 8/15 : RUN rm /bento/bundled_pip_dependencies/environment.yml
 ---> Running in 6b88bbf8bef0
Removing intermediate container 6b88bbf8bef0
 ---> 5b8fa38d2064
Step 9/15 : RUN chmod +x /bento/bentoml-init.sh /usr/local/bin/docker-entrypoint.sh
 ---> Running in 6fe8f2b0492f
Removing intermediate container 6fe8f2b0492f
 ---> 6d6979f19df5
Step 10/15 : RUN if [ -f /bento/bentoml-init.sh ]; then bash -c /bento/bentoml-init.sh; fi
 ---> Running in 152711f97c75
+++ dirname /bento/bentoml-init.sh
++ cd /bento
++ pwd -P
+ SAVED_BUNDLE_PATH=/bento
+ cd /bento
+ '[' -f ./setup.sh ']'
+ '[' -f ./python_version ']'
++ cat ./python_version
+ PY_VERSION_SAVED=3.7.1
+ DESIRED_PY_VERSION=3.7
++ python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")'
+ CURRENT_PY_VERSION=3.7
+ [[ 3.7 == \3\.\7 ]]
Python Version in docker base image 3.7 matches requirement python=3.7. Skipping.
+ echo 'Python Version in docker base image 3.7 matches requirement python=3.7. Skipping.'
+ command -v conda
+ echo 'Updating conda base environment with environment.yml'
+ conda env update -n base -f ./environment.yml
Updating conda base environment with environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages
ca-certificates-2020 | 137 KB    | ########## | 100%
python_abi-3.7       | 4 KB      | ########## | 100%
pip-20.3.1           | 1.1 MB    | ########## | 100%
readline-8.0         | 281 KB    | ########## | 100%
python-3.7.9         | 45.3 MB   | ########## | 100%
certifi-2020.12.5    | 143 KB    | ########## | 100%
openssl-1.1.1h       | 2.1 MB    | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate base
#
# To deactivate an active environment, use
#
#     $ conda deactivate

+ conda clean --all
Cache location: /opt/conda/pkgs
Will remove the following tarballs:

/opt/conda/pkgs
---------------
six-1.15.0-py_0.conda                         13 KB
ncurses-6.2-he6710b0_1.conda                 817 KB
ruamel_yaml-0.15.87-py37h7b6447c_1.conda     245 KB
pyopenssl-19.1.0-py_1.conda                   48 KB
libffi-3.3-he6710b0_2.conda                   50 KB
cryptography-2.9.2-py37h1ba5d50_0.conda      552 KB
ca-certificates-2020.6.24-0.conda            125 KB
libedit-3.1.20191231-h14c3975_1.conda        116 KB
pycparser-2.20-py_2.conda                     94 KB
cffi-1.14.1-py37he30daa8_0.conda             226 KB
openssl-1.1.1g-h7b6447c_0.conda              2.5 MB
idna-2.10-py_0.conda                          50 KB
certifi-2020.6.20-py37_0.conda               156 KB
xz-5.2.5-h7b6447c_0.conda                    341 KB
requests-2.24.0-py_0.conda                    56 KB
tqdm-4.48.2-py_0.conda                        63 KB
urllib3-1.25.10-py_0.conda                    98 KB
setuptools-49.6.0-py37_0.conda               754 KB
conda-4.8.4-py37_0.conda                     2.9 MB
sqlite-3.33.0-h62c20be_0.conda               1.1 MB
brotlipy-0.7.0-py37h7b6447c_1000.conda       322 KB
tk-8.6.10-hbc83047_0.conda                   3.0 MB
conda-package-handling-1.6.1-py37h7b6447c_0.conda     798 KB
yaml-0.2.5-h7b6447c_0.conda                   75 KB
pysocks-1.7.1-py37_1.conda                    27 KB
pip-20.3.1-pyhd8ed1ab_0.tar.bz2              1.1 MB
python-3.7.9-h7579374_0.conda               45.3 MB
ca-certificates-2020.12.5-ha878542_0.tar.bz2     137 KB
certifi-2020.12.5-py37h89c1867_0.tar.bz2     143 KB
readline-8.0-he28a2e2_2.tar.bz2              281 KB
python_abi-3.7-1_cp37m.tar.bz2                 4 KB
openssl-1.1.1h-h516909a_0.tar.bz2            2.1 MB
pip-20.3-py37h06a4308_0.conda                1.7 MB
certifi-2020.11.8-py37h06a4308_0.conda       148 KB
conda-4.9.2-py37h06a4308_0.conda             2.9 MB
ca-certificates-2020.10.14-0.conda           121 KB
wheel-0.36.0-pyhd3eb1b0_0.conda               32 KB
openssl-1.1.1h-h7b6447c_0.conda              2.5 MB

---------------------------------------------------
Total:                                      70.9 MB

Proceed ([y]/n)?
Removed six-1.15.0-py_0.conda
Removed ncurses-6.2-he6710b0_1.conda
Removed ruamel_yaml-0.15.87-py37h7b6447c_1.conda
Removed pyopenssl-19.1.0-py_1.conda
Removed libffi-3.3-he6710b0_2.conda
Removed cryptography-2.9.2-py37h1ba5d50_0.conda
Removed ca-certificates-2020.6.24-0.conda
Removed libedit-3.1.20191231-h14c3975_1.conda
Removed pycparser-2.20-py_2.conda
Removed cffi-1.14.1-py37he30daa8_0.conda
Removed openssl-1.1.1g-h7b6447c_0.conda
Removed idna-2.10-py_0.conda
Removed certifi-2020.6.20-py37_0.conda
Removed xz-5.2.5-h7b6447c_0.conda
Removed requests-2.24.0-py_0.conda
Removed tqdm-4.48.2-py_0.conda
Removed urllib3-1.25.10-py_0.conda
Removed setuptools-49.6.0-py37_0.conda
Removed conda-4.8.4-py37_0.conda
Removed sqlite-3.33.0-h62c20be_0.conda
Removed brotlipy-0.7.0-py37h7b6447c_1000.conda
Removed tk-8.6.10-hbc83047_0.conda
Removed conda-package-handling-1.6.1-py37h7b6447c_0.conda
Removed yaml-0.2.5-h7b6447c_0.conda
Removed pysocks-1.7.1-py37_1.conda
Removed pip-20.3.1-pyhd8ed1ab_0.tar.bz2
Removed python-3.7.9-h7579374_0.conda
Removed ca-certificates-2020.12.5-ha878542_0.tar.bz2
Removed certifi-2020.12.5-py37h89c1867_0.tar.bz2
Removed readline-8.0-he28a2e2_2.tar.bz2
Removed python_abi-3.7-1_cp37m.tar.bz2
Removed openssl-1.1.1h-h516909a_0.tar.bz2
Removed pip-20.3-py37h06a4308_0.conda
Removed certifi-2020.11.8-py37h06a4308_0.conda
Removed conda-4.9.2-py37h06a4308_0.conda
Removed ca-certificates-2020.10.14-0.conda
Removed wheel-0.36.0-pyhd3eb1b0_0.conda
Removed openssl-1.1.1h-h7b6447c_0.conda
WARNING: /root/.conda/pkgs does not exist
Cache location: /opt/conda/pkgs
Will remove the following packages:
/opt/conda/pkgs
---------------

python_abi-3.7-1_cp37m                        10 KB

---------------------------------------------------
Total:                                        10 KB

Proceed ([y]/n)?
removing python_abi-3.7-1_cp37m
+ pip install -r ./requirements.txt --no-cache-dir
Requirement already satisfied: bentoml==0.10.0 in /opt/conda/lib/python3.7/site-packages (from -r ./requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: prometheus-client in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.9.0)
Requirement already satisfied: cerberus in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.3.2)
Requirement already satisfied: py-zipkin in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.20.1)
Requirement already satisfied: sqlalchemy<1.4.0,>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.3.20)
Requirement already satisfied: grpcio<=1.27.2 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.27.2)
Requirement already satisfied: tabulate in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.8.7)
Requirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (20.7)
Requirement already satisfied: protobuf>=3.8.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.14.0)
Requirement already satisfied: alembic in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.4.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: docker in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (4.4.0)
Requirement already satisfied: humanfriendly in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (9.0)
Requirement already satisfied: python-json-logger in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: flask in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.1.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: aiohttp in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.7.3)
Requirement already satisfied: configparser in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (5.0.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (5.7.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.4)
Requirement already satisfied: gunicorn in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (20.0.4)
Requirement already satisfied: ruamel.yaml>=0.15.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.15.87)
Requirement already satisfied: sqlalchemy-utils<0.36.8 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.36.7)
Requirement already satisfied: chardet in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: boto3 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.16.30)
Requirement already satisfied: urllib3<=1.25.11 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.25.10)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (7.1.2)
Collecting pandas==0.25.3
  Downloading pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl (10.4 MB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.4)
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.8.1)
Collecting scikit-learn==0.23.1
  Downloading scikit_learn-0.23.1-cp37-cp37m-manylinux1_x86_64.whl (6.8 MB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.7.4.3)
Requirement already satisfied: chardet in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (20.3.0)
Requirement already satisfied: python-editor>=0.3 in /opt/conda/lib/python3.7/site-packages (from alembic->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.0.4)
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: Mako in /opt/conda/lib/python3.7/site-packages (from alembic->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.1.3)
Requirement already satisfied: sqlalchemy<1.4.0,>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.3.20)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3->bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /opt/conda/lib/python3.7/site-packages (from boto3->bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.3.3)
Requirement already satisfied: botocore<1.20.0,>=1.19.30 in /opt/conda/lib/python3.7/site-packages (from boto3->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.30)
Requirement already satisfied: urllib3<=1.25.11 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.25.10)
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.8.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3->bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.10.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from cerberus->bentoml==0.10.0->-r ./requirements.txt (line 1)) (49.6.0.post20200814)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: websocket-client>=0.32.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.57.0)
Requirement already satisfied: click>=7.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (7.1.2)
Requirement already satisfied: Werkzeug>=0.15 in /opt/conda/lib/python3.7/site-packages (from flask->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /opt/conda/lib/python3.7/site-packages (from flask->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /opt/conda/lib/python3.7/site-packages (from flask->bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.11.2)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from cerberus->bentoml==0.10.0->-r ./requirements.txt (line 1)) (49.6.0.post20200814)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.1.1)
Collecting joblib>=0.11
  Downloading joblib-0.17.0-py3-none-any.whl (301 kB)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/conda/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging->bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.4.7)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: thriftpy2>=0.4.0 in /opt/conda/lib/python3.7/site-packages (from py-zipkin->bentoml==0.10.0->-r ./requirements.txt (line 1)) (0.4.12)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Collecting pytz>=2017.2
  Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
Requirement already satisfied: urllib3<=1.25.11 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.25.10)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: chardet in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: botocore<1.20.0,>=1.19.30 in /opt/conda/lib/python3.7/site-packages (from boto3->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.30)
Collecting scipy>=0.19.1
  Downloading scipy-1.5.4-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.19.4)
Requirement already satisfied: sqlalchemy<1.4.0,>=1.3.0 in /opt/conda/lib/python3.7/site-packages (from bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.3.20)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Requirement already satisfied: ply<4.0,>=3.4 in /opt/conda/lib/python3.7/site-packages (from thriftpy2>=0.4.0->py-zipkin->bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.11)
Requirement already satisfied: six>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from docker->bentoml==0.10.0->-r ./requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->bentoml==0.10.0->-r ./requirements.txt (line 1)) (2.10)
Requirement already satisfied: typing-extensions>=3.6.5 in /opt/conda/lib/python3.7/site-packages (from aiohttp->bentoml==0.10.0->-r ./requirements.txt (line 1)) (3.7.4.3)
Installing collected packages: threadpoolctl, scipy, pytz, joblib, scikit-learn, pandas
Successfully installed joblib-0.17.0 pandas-0.25.3 pytz-2020.4 scikit-learn-0.23.1 scipy-1.5.4 threadpoolctl-2.1.0
+ '[' -d ./bundled_pip_dependencies ']'
+ pip install -U './bundled_pip_dependencies/*'
ERROR: Invalid requirement: './bundled_pip_dependencies/*'
Hint: It looks like a path. File './bundled_pip_dependencies/*' does not exist.
The command '/bin/sh -c if [ -f /bento/bentoml-init.sh ]; then bash -c /bento/bentoml-init.sh; fi' returned a non-zero code: 1

**Environment:**

OS: MacOS 10.14.6
Python Version Python 3.7
Docker. ![image](https://user-images.githubusercontent.com/4483983/101661403-394d7080-3a16-11eb-8d47-7f0b146b3778.png)

**Comment by yubozhao** [comment] 2020-12-09 18:47
@Syphixs Thank you for reporting. @cryanzpj Thanks for the bundle and the log.
I am going to check it out.

**Comment by parano** [comment] 2020-12-09 20:42
@Syphixs thanks for reporting this issue. This is a regression introduced in 0.10.0, we are working on a fix and will release a new version 0.10.1 including the fix later today.

**Comment by parano** [comment] 2020-12-11 03:05
This is now fixed in the new release 0.10.1

**Closed by parano** 2020-12-11 03:05 UTC
Labels: bug
