### ISSUE TITLE
Cannot specify bucket by self for yatai server

### ISSUE THREAD

**Issue by marclipoff** [bentoml/BentoML#842] opened 2020-06-25 16:38 UTC
**Describe the bug**
Cannot specify a s3 location with bucket along for yatai-server repo location

**To Reproduce**
docker run -p 3000:3000 -p 50051:50051 -d bentoml/yatai-service:0.8.1 --repo-base-url s3://bucket_name

This will cause the model path to be like s3://bucket_name//model
(not the double /)

Workaround is to add a path to the report-base-url, such as 
docker run -p 3000:3000 -p 50051:50051 -d bentoml/yatai-service:0.8.1 --repo-base-url s3://bucket_name/path

**Comment by yubozhao** [comment] 2020-06-30 20:17
@marclipoff This bug was resolved in version `0.7.6`.  Since that version, if only the S3 bucket is provided, the BentoService's name will become the directory name.

**Closed by yubozhao** 2020-06-30 20:17 UTC
Labels: bug

**Comment by parano** [comment] 2020-06-30 20:33
Hi @marclipoff, could you confirm the BentoML version you were using?  I can not reproduce with the command provided in the issue description with version 0.8.1
