### ISSUE TITLE
TF2 tutorial fails serving in production mode

### ISSUE THREAD

**Issue by AndreasLR** [bentoml/BentoML#2530] opened 2022-05-31 23:19 UTC
Here's an error reported by the server used in the TF2 tutorial using: `bentoml serve tensorflow_mnist_demo:latest --production`

![image](https://user-images.githubusercontent.com/78612439/171298119-b3a86a82-674a-4c35-a805-cf3b55c4e7f4.png)

I had to change service.py a bit to make it work at all: 
```
import bentoml
import numpy as np
import PIL.Image
from bentoml.io import Image, NumpyNdarray
import tensorflow as tf

mnist_runner = bentoml.tensorflow.get("tensorflow_mnist:latest").to_runner()  # Changed as per deprecation warning

svc = bentoml.Service(
    name="tensorflow_mnist_demo",
    runners=[
        mnist_runner,
    ],
)


@svc.api(
    input=NumpyNdarray(dtype="float32", enforce_dtype=True),
    output=NumpyNdarray(dtype="float32"),
)
async def predict_ndarray(inp: "np.ndarray") -> "np.ndarray":
    assert inp.shape == (28, 28)
    # We are using greyscale image and our PyTorch model expect one
    # extra channel dimension
    inp = np.expand_dims(inp, 2)
    return await mnist_runner.async_run(inp)


@svc.api(input=Image(), output=NumpyNdarray(dtype="float32"))
async def predict_image(f: PIL.Image) -> "np.ndarray":
    assert isinstance(f, PIL.Image.Image)  # Changed from isinstance(f, PIL.Image)
    arr = np.array(f) / 255.0
    assert arr.shape == (28, 28)

    # We are using greyscale image and our PyTorch model expect one
    # extra channel dimension
    arr = np.expand_dims(arr, 2).astype("float32")
    return await mnist_runner.async_run(tf.convert_to_tensor([arr]))  # Changed from mnist_runner.async_run(arr)

```

Note that serving using `bentoml serve service:svc --reload` worls.

_Originally posted by @AndreasLR in https://github.com/bentoml/BentoML/issues/2524#issuecomment-1142726111_

**Comment by larme** [comment] 2022-06-01 00:40
Hi @AndreasLR, thanks for your detailed reports. After last issue is fixed, I also found tensorflow still not working well under production mode. After some debugging I have a pr #2531 ready for review. The problem is that internally one part of our codes give `__call__` method of a model some special treatment while another part does not. I think after that pr is merged, gallery example should run fine.

**Closed** 2022-06-01 01:07 UTC

**Comment by AndreasLR** [comment] 2022-06-01 09:37
Thanks for your quick interventions, @larme . The TF2 tutorial now works, but I had to remove any usage of tensorflow in service.py as it would cause a Graph Execution error: `DNN library is not found.`. I rely on tensorflow for service.py in my own project, so I might open a new ticket if I get the time.
