### ISSUE TITLE
bug: bentoml containerize not using dockerfile_template

### ISSUE THREAD

**Issue by RobbieFernandez** [bentoml/BentoML#3491] opened 2023-01-30 04:03 UTC
### Describe the bug

When running `bentoml containerize` with a custom docker template, the additional build steps are not running. This seems to be a regression in v1.0.13 as I've confirmed that it does work for v1.0.12. When exporting the bento, I can see that the rendered Dockerfile *does* contain the additional steps but they are not being run.

I believe this is related to this change, https://github.com/bentoml/BentoML/pull/3400. It looks like to me like the template gets re-rendered without the custom content when running `containerize`. 

### To reproduce

Run `bentoml containerize` with a custom template. Additional steps will not be run.

### Expected behavior

`bentoml containerize` should run the additional build steps from the dockerfile_template.

#### Environment variable

```bash
BENTOML_DEBUG=''
BENTOML_QUIET=''
BENTOML_BUNDLE_LOCAL_BUILD=''
BENTOML_DO_NOT_TRACK=''
BENTOML_CONFIG=''
BENTOML_CONFIG_OPTIONS=''
BENTOML_PORT=''
BENTOML_HOST=''
BENTOML_API_WORKERS=''
```

#### System information

`bentoml`: 1.0.13
`python`: 3.10.6
`platform`: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
`uid_gid`: 1000:1000
<details><summary><code>pip_packages</code></summary>

<br>

```
absl-py==1.4.0
afid-bento @ git+ssh://git@github.com/AutomatedFishID/afid-bento.git@61868fcb2b01cae42861c575088e39447b49193f
aiohttp==3.8.3
aiosignal==1.3.1
anyio==3.6.2
appdirs==1.4.4
asgiref==3.6.0
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
backcall==0.2.0
backoff==2.2.1
bentoml==1.0.13
boto3==1.26.59
botocore==1.29.59
build==0.10.0
cachetools==5.3.0
cattrs==22.2.0
certifi==2022.12.7
charset-normalizer==2.1.1
circus==0.18.0
click==8.0.4
click-option-group==0.5.5
cloudpickle==2.2.1
contextlib2==21.6.0
contourpy==1.0.7
cycler==0.11.0
decorator==5.1.1
deepmerge==1.1.0
Deprecated==1.2.13
exceptiongroup==1.1.0
executing==1.2.0
fastapi==0.89.1
filelock==3.9.0
filetype==1.2.0
fire==0.5.0
fonttools==4.38.0
frozenlist==1.3.3
fs==2.4.16
gitdb==4.0.10
GitPython==3.1.30
google-auth==2.16.0
google-auth-oauthlib==0.4.6
googleapis-common-protos==1.58.0
grpcio==1.51.1
h11==0.14.0
hiredis==2.1.1
huggingface-hub==0.12.0
idna==3.4
install==1.3.5
ipdb==0.13.11
ipython==8.9.0
jedi==0.18.2
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
Markdown==3.4.1
markdown-it-py==2.1.0
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mdurl==0.1.2
multidict==6.0.4
numpy==1.24.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
opencv-python==4.7.0.68
opentelemetry-api==1.14.0
opentelemetry-exporter-otlp-proto-http==1.14.0
opentelemetry-instrumentation==0.35b0
opentelemetry-instrumentation-aiohttp-client==0.35b0
opentelemetry-instrumentation-asgi==0.35b0
opentelemetry-proto==1.14.0
opentelemetry-sdk==1.14.0
opentelemetry-semantic-conventions==0.35b0
opentelemetry-util-http==0.35b0
packaging==21.3
pandas==1.5.3
parso==0.8.3
pathspec==0.11.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
pip-requirements-parser==32.0.1
pip-tools==6.12.1
prometheus-client==0.16.0
prompt-toolkit==3.0.36
protobuf==3.20.3
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybboxes==0.1.6
pydantic==1.10.4
Pygments==2.14.0
pynvml==11.4.1
pyparsing==3.0.9
pyproject_hooks==1.0.0
python-dateutil==2.8.2
python-json-logger==2.0.4
python-multipart==0.0.5
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
redis==4.4.2
requests==2.28.2
requests-oauthlib==1.3.1
rich==13.3.1
rsa==4.9
s3transfer==0.6.0
sahi==0.11.11
schema==0.7.5
scipy==1.10.0
seaborn==0.12.2
shapely==2.0.0
simple-di==0.1.5
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
stack-data==0.6.2
starlette==0.22.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
termcolor==2.2.0
terminaltables==3.1.10
thop==0.1.1.post2209072238
tomli==2.0.1
torch==1.13.1
torchvision==0.14.1
tornado==6.2
tqdm==4.64.1
traitlets==5.8.1
typing_extensions==4.3.0
urllib3==1.26.14
uvicorn==0.20.0
watchfiles==0.18.1
wcwidth==0.2.6
Werkzeug==2.2.2
wrapt==1.14.1
yarl==1.8.2
yolov5==7.0.7
```

</details>

**Comment by aarnphm** [comment] 2023-01-30 10:16
Hi there, I can still see the custom Dockerfile templates after containerize. Can you send your `bentofile.yaml` and the custom templates that you are using?

**Comment by RobbieFernandez** [comment] 2023-01-31 02:35
Unfortunately I'm not able to share the actual code that I'm having this issue with, but I've created a small GitHub repo to demonstrate the issue: https://github.com/RobbieFernandez/bentoml-containerize-reproduction

Here's the bento created from the repo (renamed to .zip so GitHub will allow it)
[test-f72nscfbb64ntw2b.zip](https://github.com/bentoml/BentoML/files/10542041/test-f72nscfbb64ntw2b.zip)

The bento file does have the correct Dockerfile in it, but when I run containerize it does not include the extra `apt` step. Here is the output:
```
(venv) robbie@elitebook:bento-containerize-issue$ bentoml containerize test:f72nscfbb64ntw2b
Building OCI-compliant image for test:f72nscfbb64ntw2b with docker

[+] Building 12.4s (15/15) FINISHED                                                                                          
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 1.66kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                       0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                     1.8s
 => [base-container  1/10] FROM docker.io/library/python:3.10-slim@sha256:e04bc5390a13e6e910980715f1156552fbd3deddf766  0.0s
 => [internal] load build context                                                                                       0.0s
 => => transferring context: 13.71kB                                                                                    0.0s
 => CACHED [base-container  2/10] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-  0.0s
 => CACHED [base-container  3/10] RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt   0.0s
 => CACHED [base-container  4/10] RUN groupadd -g 1034 -o bentoml && useradd -m -u 1034 -g 1034 -o -r bentoml           0.0s
 => CACHED [base-container  5/10] RUN mkdir /home/bentoml/bento && chown bentoml:bentoml /home/bentoml/bento -R         0.0s
 => CACHED [base-container  6/10] WORKDIR /home/bentoml/bento                                                           0.0s
 => [base-container  7/10] COPY --chown=bentoml:bentoml . ./                                                            0.0s
 => [base-container  8/10] RUN --mount=type=cache,target=/root/.cache/pip bash -euxo pipefail /home/bentoml/bento/env/  8.9s
 => [base-container  9/10] RUN rm -rf /var/lib/{apt,cache,log}                                                          0.4s
 => [base-container 10/10] RUN chmod +x /home/bentoml/bento/env/docker/entrypoint.sh                                    0.5s 
 => exporting to image                                                                                                  0.6s 
 => => exporting layers                                                                                                 0.6s 
 => => writing image sha256:b2ee489ab0703da26e2324a95702f19a8275b0817097f8419aca4c7d85b93eee                            0.0s 
 => => naming to docker.io/library/test:f72nscfbb64ntw2b                                                                0.0s 
Successfully built Bento container for "test:f72nscfbb64ntw2b" with tag(s) "test:f72nscfbb64ntw2b"
To run your newly built Bento container, run:
    docker run -it --rm -p 3000:3000 test:f72nscfbb64ntw2b serve --production
```

And here is the output when running `containerize` on v 1.0.12. Note the additional step at `[base-container 8/11]` which is not run on v1.0.11:
```
(venv) robbie@elitebook:bento-containerize-issue$ bentoml containerize test:f72nscfbb64ntw2b
Building OCI-compliant image for test:f72nscfbb64ntw2b with docker

[+] Building 25.9s (16/16) FINISHED                                                                                          
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 1.87kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                       0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load metadata for docker.io/library/python:3.10-slim                                                     0.9s
 => [internal] load build context                                                                                       0.0s
 => => transferring context: 13.92kB                                                                                    0.0s
 => [base-container  1/11] FROM docker.io/library/python:3.10-slim@sha256:e04bc5390a13e6e910980715f1156552fbd3deddf766  0.0s
 => CACHED [base-container  2/11] RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-  0.0s
 => CACHED [base-container  3/11] RUN --mount=type=cache,target=/var/lib/apt --mount=type=cache,target=/var/cache/apt   0.0s
 => CACHED [base-container  4/11] RUN groupadd -g 1034 -o bentoml && useradd -m -u 1034 -g 1034 -o -r bentoml           0.0s
 => CACHED [base-container  5/11] RUN mkdir /home/bentoml/bento && chown bentoml:bentoml /home/bentoml/bento -R         0.0s
 => CACHED [base-container  6/11] WORKDIR /home/bentoml/bento                                                           0.0s
 => [base-container  7/11] COPY --chown=bentoml:bentoml . ./                                                            0.0s
 => [base-container  8/11] RUN apt update &&     apt install -y         git         openssh-client         zlib1g-dev  12.9s
 => [base-container  9/11] RUN --mount=type=cache,target=/root/.cache/pip bash -euxo pipefail /home/bentoml/bento/env  10.0s
 => [base-container 10/11] RUN rm -rf /var/lib/{apt,cache,log}                                                          0.4s 
 => [base-container 11/11] RUN chmod +x /home/bentoml/bento/env/docker/entrypoint.sh                                    0.2s 
 => exporting to image                                                                                                  1.3s 
 => => exporting layers                                                                                                 1.3s 
 => => writing image sha256:81a75df2283770e3df48bb8fd59892e5636329bee96fb5884c7f7b3fc6382d4c                            0.0s 
 => => naming to docker.io/library/test:f72nscfbb64ntw2b                                                                0.0s 
Successfully built Bento container for "test:f72nscfbb64ntw2b" with tag(s) "test:f72nscfbb64ntw2b"
To run your newly built Bento container, use 'test:f72nscfbb64ntw2b' as a tag and pass it to 'docker run'. For example:
    docker run -it --rm -p 3000:3000 test:f72nscfbb64ntw2b serve --production
```
Note that I did not re-run `bentoml build` in-between these calls to `containerize` so they're being run on the exact same bento. That should confirm that the bento file itself is correct, but some logic in the `containerize` code has regressed.

**Comment by aarnphm** [comment] 2023-01-31 05:39
Thanks for the test repo. I have been able to reproduce it.

Btw you can use `system_packages` to define list of system packages from ubuntu in the `bentofile.yaml` for now:

```yaml
docker:
  system_packages:
    - ...
    - ...
```

I will put up a test PR promptly.

**Comment by RobbieFernandez** [comment] 2023-01-31 06:06
Thanks. I'm actually using it for more than jusf the apt install but that seemed an easy way to demonstrate the issue. For now I'll stay on 1.0.12

**Comment by aarnphm** [comment] 2023-02-01 02:04
Hi @RobbieFernandez, I put up https://github.com/bentoml/BentoML/pull/3501, which will solve the issue at hand.

This will be included in the upcoming release. Thank you for reporting the bug.

**Comment by RobbieFernandez** [comment] 2023-02-16 01:48
Hi @aarnphm, I see there have been some releases since that PR was merged. Is the fix included in any of those releases?

**Comment by aarnphm** [comment] 2023-02-16 02:39
Not yet. The PR hasn't got merged yet 😿

**Comment by RobbieFernandez** [comment] 2023-02-16 03:03
Ok no worries, I just saw that #3501 was merged and thought that was the fix

**Comment by aarnphm** [comment] 2023-02-16 03:08
oh that was actually the fix. I didn't know it got merged in for 1.0.15 😄 

Feel free to try it out now if it fixes the issue for you.

**Comment by RobbieFernandez** [comment] 2023-02-16 08:10
Looks like it's now working in 1.0.15 :tada: Thanks!

**Comment by aarnphm** [comment] 2023-02-16 11:40
Closing since the bug is addressed.

**Closed by aarnphm** 2023-02-16 11:40 UTC
Labels: bug
