### ISSUE TITLE
[BUG] BentoML bentoml.container.build looks for "=" in platform argument 

### ISSUE THREAD

**Issue by drsantos89** [bentoml/BentoML#3365] opened 2022-12-15 10:26 UTC
When using the "bentoml.container.build" to containerise a service, if a platform is specified, the code in the link below looks for the "=" sign and fails with an index error:
```JSON
"name": "IndexError",
"message": "list index out of range",
```
https://github.com/bentoml/BentoML/blob/98f6f63cfe0242a8df230fed00aa323a29735372/src/bentoml/container.py#L404
Removing line 404 fixed the issue.
Example code:
```python
import bentoml
bentoml.container.build(
    bento_tag="<service>:<version>",
    tag="<service>:<version>",
    platform="linux/amd64",
)

**Comment by ruial** [comment] 2023-01-02 11:37
Hey @aarnphm, any update? Currently ```bentoml containerize <bento> --opt platform=linux/amd64``` is broken on the latest version.

**Comment by aarnphm** [comment] 2023-01-03 03:42
Hi @ruial, This will be fixed by #3366

**Comment by aarnphm** [comment] 2023-01-06 20:34
I will close this once the next release is out.

**Comment by phitoduck** [comment] 2023-01-17 22:33
I may have just opened a duplicate of this issue. My description may add helpful context to this issue: #3440

**Closed** 2023-01-20 03:11 UTC
Labels: fixed-in-main
