### ISSUE TITLE
got internal server error when trying to invoke sagemaker endpoint

### ISSUE THREAD

**Issue by palver7** [bentoml/BentoML#742] opened 2020-05-30 02:01 UTC
**Describe the bug**
I am following the tutorial described in https://docs.bentoml.org/en/latest/deployment/aws_sagemaker.html. I got the expected results until I get to this part
![command that causes error](https://user-images.githubusercontent.com/42964197/83316687-6e039280-a251-11ea-835f-d0c459f250f8.png)

Instead of the output with the red characters, I got this message : 
![error on terminal](https://user-images.githubusercontent.com/42964197/83316763-10237a80-a252-11ea-9409-6ae6d666d6dc.png)

I did as the message said and checked the associated CloudWatch log and this are the error messages 
![cloudwatch error logs](https://user-images.githubusercontent.com/42964197/83316799-5082f880-a252-11ea-8b3d-a45b331273ba.png)

**To Reproduce**
1. follow the tutorial described in  https://docs.bentoml.org/en/latest/deployment/aws_sagemaker.html . (The only thing different is the region, I set it to ap-southeast-1)

**Expected behavior**
the output should be like the first screenshot above.

**Environment:**
 - OS: [Linux Mint 19.3 Tricia Cinnamon]
 - Python/BentoML Version [e.g. Python 3.7.4, BentoML 0.7.8]

**Additional context**
What I tried  to solve this error: 
The first message about unpickling svm created with scikit-learn 0.21.3 with scikit-learn 0.23.1 may causes errors made me upgrade my local scikit-learn package from 0.21.3 to 0.23.1 but it did nothing. I assume that the scikit-learn package referred here is the scikit-learn inside the docker image for aws sagemaker ?

**Comment by palver7** [comment] 2020-06-01 10:55
@yubozhao update: I tried another tutorial, this time the tensorflow Fashion-MNIST classifier (https://github.com/bentoml/gallery/blob/master/tensorflow/fashion-mnist/tensorflow_2_fashion_mnist.ipynb) and tried the to deploy the bentoML service to AWS sagemaker. I ran the tutorial with JupyterLab on my computer.  When I get to the invoke endpoint step, a similar error occurred :

![error in jupyterlab](https://user-images.githubusercontent.com/42964197/83401771-c55f5980-a42f-11ea-8172-c863ca0d3a22.png)

and the CloudWatch logs show these error messages :   

![cloudwatch error tensorflow](https://user-images.githubusercontent.com/42964197/83402263-9695b300-a430-11ea-9a01-6f1bb4acbe86.png)

It seems that the bug is not specific to iris classifier tutorial then.

**Comment by yubozhao** [comment] 2020-06-01 20:23
Hi @palver7 

It looks like this could be an issue of decoding `request.data` for the web server. I was unable to reproduce it with the fashion mnist example notebook with the latest master branch with the latest commit of 5d23859b. 

Can you tell me which BentoML version or commit you are on when you create the BentoService and deploy it to the Sagemaker?

Also, could you try to make an request locally, when you start a local webserver with `bentoml serve BENTO_SERVICE_NAME:VERSION`? This would be faster to try out compare to deploy to Sagemaker.

**Comment by palver7** [comment] 2020-06-02 04:23
@yubozhao  Here is the bentoml.yml file

![bentoml-yml](https://user-images.githubusercontent.com/42964197/83476487-1700f600-a4bb-11ea-8453-42f756123bf5.png)

Regarding point 1, how to check the encoding of the request ?

About point 3. I ran the docker and ran the curl request but I get a 400 bad request error

![bad request error](https://user-images.githubusercontent.com/42964197/83479587-3734b300-a4c3-11ea-8a78-a90805b6b003.png)

**Comment by yubozhao** [comment] 2020-06-02 04:29
@palver7 for bullet point 1.  Can you try either `echo $LC_CTYPE` and/or `echo $LANG` in your terminal and see what is the result is?
For my MacOS, the value is `en_US.UTF-8`. Yours should be something similar.

**Comment by palver7** [comment] 2020-06-02 05:09
@yubozhao  typing echo $LC_CTYPE prints empty line but typing echo $LANG prints en_US.UTF-8

**Comment by parano** [comment] 2020-06-02 06:17
Hi @palver7 could you share what's the output of `file -i test.json` after the `echo ...` line?

Could you also try sending the prediction request from the docker container running the API server? You will need to first get the ID of the docker container running the BentoML model server, it can be found in the `docker ps` list after running the container. You can access the running container with the follow command:

```bash
docker exec -it 3afe2f815c3b bash
```

And then within the container, try sending the request to localhost:

```bash
apt-get update
apt-get install curl
echo "..." > test.json
curl ...
```

**Comment by palver7** [comment] 2020-06-02 07:50
the output of file -i test.json: test.json: text/plain; charset=us-ascii
sending the request to localhost inside the container still give the same error message as before : 

![2nd_bad_request_error](https://user-images.githubusercontent.com/42964197/83494415-6f96ba00-a4e0-11ea-90b8-8c7c9be6362a.png)

**Comment by parano** [comment] 2020-06-24 04:30
Hi @palver7, sorry for the delayed reply on this one,  could you add `-v` option to your curl command so we can see the full request header? thanks!

**Comment by palver7** [comment] 2020-06-24 16:17
> Hi @palver7, sorry for the delayed reply on this one, could you add `-v` option to your curl command so we can see the full request header? thanks!

@parano, here is the output with the test.json created as directed

![curl error message](https://user-images.githubusercontent.com/42964197/85592892-c1aaa580-b670-11ea-98cf-48c5c34e8c57.png)

**Comment by parano** [comment] 2020-06-24 16:31
@palver7 did you specify content-type header in this CURL command? could you include the curl command used in the screenshot?

**Comment by palver7** [comment] 2020-06-24 16:35
![curl error message](https://user-images.githubusercontent.com/42964197/85595666-439bce00-b673-11ea-8f32-825d7e967a19.png)

@parano here is the screenshot with command included

**Comment by parano** [comment] 2020-06-24 16:41
@palver7  I see, I think it should not be `--data-binary` in this case, can you try changing it from `--data-binary @test.json` to `-d @test.json` instead?

**Comment by palver7** [comment] 2020-06-24 16:48
@parano with this command : curl -X POST "http://127.0.0.1:5000/predict" -H "Content-Type: application/json" -d @test.json -v 

the error message is still the same, ending with 

<p>The browser (or proxy) sent a request that this server could not understand.</p>
* Closing connection 0

**Comment by palver7** [comment] 2020-06-26 13:20
@Parano I have four  cases in trying to deploy prediction on my local machine: 

1. if I change the content of test.json file from 
{\"instances\":[{\"b64\":\"...\"}]}
to
{"instances":[{"b64":"..."}]}
and run the the curl as above then I get "Ankle boot" with no error messages. 

2. if I changed the test.json file as above but implementing my custom tensorflow handler class in the service bundle file as per your suggestion I got the error. 

![curl error custom handler](https://user-images.githubusercontent.com/42964197/85860766-7bc51d00-b7e9-11ea-9782-a4952776cc8a.png) 

3. If I do as 2. but creating the custom tensor handler class by copy pasting the content of the tensorflow tensor handler.py into the service bundle python file then I get the prediction "Ankle boot". 

4. Finally, whether I created the custom tensor handler class or not, if I left the content of the test.json file as generated by the notebook tutorial :
{\"instances\":[{\"b64\":\"...\"}]}
I would get the bad request and the proxy sent a request that the server could not understand like the previous post.

**Comment by parano** [comment] 2020-07-12 03:07
Hey @palver7 - are you still experiencing this issue with the latest release of BentoML?  It might be helpful for us to do a quick call and have you show me how you reproduce the issue and we can do an interactive debug session.  Feel free to ping me in the BentoML community slack channel if you'd like to do that.

**Comment by palver7** [comment] 2020-07-14 12:25
> Hey @palver7 - are you still experiencing this issue with the latest release of BentoML? It might be helpful for us to do a quick call and have you show me how you reproduce the issue and we can do an interactive debug session. Feel free to ping me in the BentoML community slack channel if you'd like to do that.

What time are you available for the interactive debug session ?

**Comment by parano** [comment] 2020-07-14 16:53
@palver7 could you email me or DM me in BentoML slack?

**Comment by parano** [comment] 2020-07-20 16:09
Discussed with @palver7 - turns out this is an issue with our gallery notebook:
https://github.com/bentoml/gallery/blob/master/tensorflow/fashion-mnist/tensorflow_2_fashion_mnist.ipynb

Closing this issue for now since the descriptions and discussions here are no longer relevant to this issue. We will investigate the issue with the tensorflow_2_fashion_mnist notebook and open a new issue if necessary.

Thanks @palver7

**Closed by parano** 2020-07-20 16:09 UTC
Labels: bug
