### ISSUE TITLE
Can't change default values in @bentoml.artifacts

### ISSUE THREAD

**Issue by harshitsinghai77** [bentoml/BentoML#1535] opened 2021-03-25 11:40 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/30886142/112466981-7c94da80-8d8c-11eb-924f-9f633c271565.png)

For example, in this case I'm not able to overwrite `model_extension`

I think this might be because of this.
https://github.com/bentoml/BentoML/blob/master/bentoml/service/artifacts/__init__.py#L109

It's not passing the arguments and hence the default values is always used. 

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Environment:**
 - OS: [e.g. MacOS 10.14.3]
 - Python Version [e.g. Python 3.7.1]
 - BentoML Version [e.g. BentoML-0.8.6]

**Additional context**

**Comment by harshitsinghai77** [comment] 2021-03-25 14:47
I'm trying to do something like this

![image](https://user-images.githubusercontent.com/30886142/112492132-0487de00-8da7-11eb-81ae-b2c672c384d1.png)

But this doesn't get picked up. 

![image](https://user-images.githubusercontent.com/30886142/112492283-21241600-8da7-11eb-9302-7c4b9e1bef17.png)

**Comment by harshitsinghai77** [comment] 2021-03-25 14:48
^ the `model_type` should be `classifier` but I'm still getting `catboost`

**Comment by harshitsinghai77** [comment] 2021-03-25 17:07
Update: This happens only when testing tests with `pytest`

**Comment by yubozhao** [comment] 2021-03-25 20:58
@harshitsinghai77 Thank you for reporting this.  We are aware of this issue. 

The issue is caused here.  We need a more robust way to handle additional options.
https://github.com/bentoml/BentoML/blob/ce9bdd4fd8e1730d5c47d6c7ddcf4deddc272505/bentoml/service/artifacts/__init__.py#L104-L109

**Comment by parano** [comment] 2021-03-25 21:12
This is previously tracked here: https://github.com/bentoml/BentoML/issues/1219

**Comment by harshitsinghai77** [comment] 2021-03-26 04:26
I'm working on [this feature](https://github.com/bentoml/BentoML/issues/1327). So should I wait for the issue to get resolved or go ahead with the PR?

**Comment by parano** [comment] 2021-06-20 23:33
@harshitsinghai77 this issue is now fixed on master, feel free to revisit your work on CatBoost

**Closed by parano** 2021-06-20 23:33 UTC
Labels: bug
