### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/HenryDashwood/bentoml/node_modules/.bin/serverless': '/Users/HenryDashwood/bentoml/node_modules/.bin/serverless'

### ISSUE THREAD

**Issue by HenryDashwood** [bentoml/BentoML#354] opened 2019-10-19 17:43 UTC
When I run ```!bentoml --verbose deployment create facial-features-detector --bento {bento_tag} --platform aws-lambda --region us-east-1``` in [this notebook](https://github.com/HenryDashwood/facial-features-detector/blob/master/code/pytorch.ipynb) I get the following error:
```
[2019-10-19 18:30:56,302] DEBUG - Using BentoML with local Yatai server
[2019-10-19 18:30:56,432] DEBUG - Upgrading tables to the latest revision
[2019-10-19 18:30:56,680] DEBUG - Created temporary directory: /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-rcsbrk64
Traceback (most recent call last):
  File "/Users/HenryDashwood/miniconda3/envs/py37/bin/bentoml", line 10, in <module>
    sys.exit(cli())
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/bentoml/cli/deployment.py", line 348, in create
    spec=spec,
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/bentoml/yatai/yatai_service_impl.py", line 121, in ApplyDeployment
    response = operator.apply(request.deployment, self, previous_deployment)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/bentoml/deployment/serverless/aws_lambda.py", line 188, in apply
    template,
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/bentoml/deployment/serverless/serverless_utils.py", line 133, in init_serverless_project_dir
    ["create", "--template", template_type, "--name", deployment_name], project_dir
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/site-packages/bentoml/deployment/serverless/serverless_utils.py", line 87, in call_serverless_command
    with subprocess.Popen(command, cwd=cwd_path, stdout=PIPE, stderr=PIPE) as proc:
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/HenryDashwood/miniconda3/envs/py37/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/HenryDashwood/bentoml/node_modules/.bin/serverless': '/Users/HenryDashwood/bentoml/node_modules/.bin/serverless'
```
I have node installed but is there another step, possibly involving npm, that I should be performing?

**Comment by yubozhao** [comment] 2019-10-20 21:00
hi @HenryDashwood, Thanks for reporting it.

I looked into your notebook that you linked. It looks fine.  I suspect there might be problem during install `serverless` framework that we aren't properly raising exception with.  

There are few things that you can help me with to better understanding this and solve this issue.
   * Could you provide your node version and npm version for me?  You can use `node --version` and `npm version` commands to get the outputs.
   * Could you navigate to your bentoml directory `/Users/HenryDashwood/bentoml` and check is the directory `node_modules` and the file `node_modules/.bin/serverless` present?

These info should help me narrow down the issue and get it fix.

**Comment by HenryDashwood** [comment] 2019-10-21 20:08
I'm on Node version 10.16.3 and NPM version 6.9.0. Mysteriously, there is no node_modules inside the bentoml directory.

**Comment by yubozhao** [comment] 2019-10-21 20:41
@HenryDashwood Thanks for the info.  I think we need to surface the error, instead of silently fails it.  I will work on to improve that part.

In the mean time, if you want to continue the deployment to AWS lambda, you could manually install `serverless`.  You can navigate to your bentoml directory, `/Users/HenryDashwood/bentoml` and run command `npm install serverless@1.53.0`.  After the installation, you could call the create deployment command again.

PS. Please make sure you use `delete --force` to remove the previous failed deployment.

Please ping me, if you run into any issues in this process.  Thanks!

**Comment by HenryDashwood** [comment] 2019-10-21 23:13
This helped. I had to also run ```npm init``` to advance. Thank you for your advice once again!

**Comment by yubozhao** [comment] 2019-10-22 23:23
Thanks for the update @HenryDashwood, glad it helped you.

It is interesting that you run `npm init` to advance.  I tested it in a new docker container and run `npm install serverless@1.53.0` without `npm init` is fine, and download the package correctly.

If you did run into error or issues with `npm install` without `npm init`.  Could you reproduce it and copy the errors or info for me?  I would like to figure out the root cause.  

You could reproduce it right in the `bentoml` directory, with these steps:
* `rm -rf node_modules`
* `rm package-lock.json`  and/or `rm package.json` if you have one
* `npm install serverless@1.53.0`

Thank you for helping us improving this project!

**Comment by HenryDashwood** [comment] 2019-10-26 16:03
Yeah, I mean those steps just don't seem to work. To create the node_modules directory and avoid the error above I need to 
```
cd bentoml
npm install 
npm init
npm install serverless@1.53.0
```

**Comment by yubozhao** [comment] 2019-10-26 17:36
Got it. Thanks for taking the extra time to help me out on this issue. 

I will do more testing on this and I will include the `npm init` as part of the operation. 

Also just FYI, once you have Serverless module, you shouldn’t encounter this issue again. If you do, feel free to ping me whenever. 

I will keep this issue open until I add in the `npm init` step


Thanks for reporting!

**Comment by HenryDashwood** [comment] 2019-10-27 15:26
No worries. Thanks for your help! I'm afraid I may need to ask you to indulge me with another error that's been occuring. Upon running deploy, Serverless seems to have trouble collecting the torch module. It looks like it might be related [this issue](https://github.com/pytorch/pytorch/issues/15213) but I'm not sure. I tried including ```torch>=1.3``` in the pip_dependencies list but the same issue arose. 
 
```
[2019-10-27 15:17:28,669] DEBUG - Using BentoML with local Yatai server
[2019-10-27 15:17:28,799] DEBUG - Upgrading tables to the latest revision
[2019-10-27 15:17:29,605] DEBUG - Created temporary directory: /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1
[2019-10-27 15:18:14,281] DEBUG - sls cmd output: Serverless: Generating boilerplate...
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v1.53.0
 -------'

Serverless: Successfully generated boilerplate for template: "aws-python3"

[2019-10-27 15:18:18,079] INFO - Installing additional packages: serverless-python-requirements
[2019-10-27 15:18:26,824] DEBUG - sls cmd output: Serverless: Creating an empty package.json file in your service directory
Serverless: Installing plugin "serverless-python-requirements@latest" (this might take a few seconds...)
Serverless: Successfully installed "serverless-python-requirements@latest"

[2019-10-27 15:18:26,825] INFO - Deploying to AWS Lambda
[2019-10-27 15:20:09,112] DEBUG - sls cmd output: Serverless: Adding Python requirements helper...
Serverless: Generated requirements from /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/requirements.txt in /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/.serverless/requirements.txt...
Serverless: Installing requirements from /Users/HenryDashwood/Library/Caches/serverless-python-requirements/9d4ebdc57e232429d00a33fc7f0b444d9a747415ca7043992e0720b472bd2661_slspyc/requirements.txt ...
Serverless: Docker Image: lambci/lambda:build-python3.7
Serverless: Using download cache directory /Users/HenryDashwood/Library/Caches/serverless-python-requirements/downloadCacheslspyc
Serverless: Running docker run --rm -v /Users/HenryDashwood/Library/Caches/serverless-python-requirements/9d4ebdc57e232429d00a33fc7f0b444d9a747415ca7043992e0720b472bd2661_slspyc\:/var/task\:z -v /Users/HenryDashwood/Library/Caches/serverless-python-requirements/downloadCacheslspyc\:/var/useDownloadCache\:z -u 0 -v /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/bundled_pip_dependencies\:/var/task/bundled_pip_dependencies\:z lambci/lambda\:build-python3.7 /bin/sh -c 'python3.7 -m pip install -t /var/task/ -r /var/task/requirements.txt --cache-dir /var/useDownloadCache && find /var/task -name \\*.so -exec strip \\{\\} \\;'...
 
  Error --------------------------------------------------
 
  Error: STDOUT: Collecting bentoml==0.4.8
    Using cached https://files.pythonhosted.org/packages/b0/07/7d1f4c6c7a476c8dd54efe9a444983ca7b1cea0420562f77ecdf20474804/BentoML-0.4.8-py3-none-any.whl
  Collecting fastai
    Using cached https://files.pythonhosted.org/packages/94/58/d78c39b2fcbe3358a54a4042219eaf78bc196e771dc02a6f540ee2194a2e/fastai-1.0.59.tar.gz
  Collecting henrys_model_utils
    Using cached https://files.pythonhosted.org/packages/6a/88/20d5d79cf0cd57b8512495fb70f1089fbc86f2bc56ec6cc371d31b21ab07/henrys_model_utils-0.1-py3-none-any.whl
  Collecting imageio
    Using cached https://files.pythonhosted.org/packages/1a/de/f7f985018f462ceeffada7f6e609919fbcc934acd9301929cba14bc2c24a/imageio-2.6.1-py3-none-any.whl
  Processing /var/useDownloadCache/wheels/e1/41/5e/e201f95d90fc84f93aa629b6638adacda680fe63aac47174ab/tabulate-0.8.5-cp37-none-any.whl
  Collecting configparser
    Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
  Collecting docker
    Using cached https://files.pythonhosted.org/packages/cc/ca/699d4754a932787ef353a157ada74efd1ceb6d1fc0bfb7989ae1e7b33111/docker-4.1.0-py2.py3-none-any.whl
  Collecting six
    Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Collecting humanfriendly
    Using cached https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl
  Collecting ruamel.yaml>=0.15.0
    Using cached https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
  Collecting boto3
    Using cached https://files.pythonhosted.org/packages/0e/41/27fb3969a76240d4c42a8f64b9d5ae78c676bab38e980e03b1bbaef279bd/boto3-1.10.2-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/97/f7/a1/752e22bb30c1cfe38194ea0070a5c66e76ef4d06ad0c7dc401/python_json_logger-0.1.11-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/4b/b2/89/cd2231ee623987c605f049df55f40a3e4252ef6a15b94836c2/SQLAlchemy-1.3.10-cp37-cp37m-linux_x86_64.whl
  Collecting flask
    Using cached https://files.pythonhosted.org/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/1c/54/34/fd47cd9b308826cc4292b54449c1899a30251ef3b506bc91ea/prometheus_client-0.7.1-cp37-none-any.whl
  Collecting requests
    Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/59/b1/91/f02e76c732915c4015ab4010f3015469866c1eb9b14058d8e7/dill-0.3.1.1-cp37-none-any.whl
  Collecting protobuf>=3.6.0
    Using cached https://files.pythonhosted.org/packages/d7/34/02a2083afc14adff644a1e29783f276f12f1f914ca4cab157d73bb3d2fed/protobuf-3.10.0-cp37-cp37m-manylinux1_x86_64.whl
  Collecting numpy
    Using cached https://files.pythonhosted.org/packages/00/4a/e34fce8f18c0e052c2b49f1b3713469d855f7662d58ae2b82a88341e865b/numpy-1.17.3-cp37-cp37m-manylinux1_x86_64.whl
  Processing /var/useDownloadCache/wheels/c6/b8/fd/1f16371156a8184172c4935cbbef6a345d57dd447e31a36633/alembic-1.2.1-py2.py3-none-any.whl
  Collecting gunicorn
    Using cached https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/4f/b4/2b/83fc9a02bdbb49350a9eeb6d34753e4d7df7f77cb027e1d4b3/Cerberus-1.3.1-cp37-none-any.whl
  Collecting packaging
    Using cached https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
  Collecting click>=7.0
    Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
  Collecting grpcio
    Using cached https://files.pythonhosted.org/packages/b9/ba/254011b066e6675411ba913dafd6e40ce8d3235bebf64fb226a7305f29ac/grpcio-1.24.3-cp37-cp37m-manylinux2010_x86_64.whl
  Collecting pandas
    Using cached https://files.pythonhosted.org/packages/91/9d/217fc3c4fe19123fcb99385a35c3211e65d5eb07fbe8dd0008fae0d1fe74/pandas-0.25.2-cp37-cp37m-manylinux1_x86_64.whl
  Collecting pathlib2
    Using cached https://files.pythonhosted.org/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
  Processing /var/useDownloadCache/wheels/f2/bf/ec/e0f39aa27001525ad455139ee57ec7d0776fe074dfd78c97e4/Bottleneck-1.2.1-cp37-cp37m-linux_x86_64.whl
  Collecting fastprogress>=0.1.19
    Using cached https://files.pythonhosted.org/packages/83/db/794db47024a26c75635c35f0ee5431aa8b528e895ad1ed958041290f83f7/fastprogress-0.1.21-py3-none-any.whl
  Collecting beautifulsoup4
    Using cached https://files.pythonhosted.org/packages/3b/c8/a55eb6ea11cd7e5ac4bacdf92bac4693b90d3ba79268be16527555e186f0/beautifulsoup4-4.8.1-py3-none-any.whl
  Collecting matplotlib
    Using cached https://files.pythonhosted.org/packages/19/7a/60bd79c5d79559150f8bba866dd7d434f0a170312e4d15e8aefa5faba294/matplotlib-3.1.1-cp37-cp37m-manylinux1_x86_64.whl
  Collecting numexpr
    Using cached https://files.pythonhosted.org/packages/2c/69/274c2b81b9bdf7783150461c8982f23248dc917402ed4c6f8aa4b90bb98e/numexpr-2.7.0-cp37-cp37m-manylinux1_x86_64.whl
  Processing /var/useDownloadCache/wheels/e4/1d/06/640c93f5270d67d0247f30be91f232700d19023f9e66d735c7/nvidia_ml_py3-7.352.0-cp37-none-any.whl
  Collecting Pillow
    Using cached https://files.pythonhosted.org/packages/89/3e/31c2e5385d7588016c6f7ac552e81c3fff2bef4bc61b6f82f8177752405c/Pillow-6.2.1-cp37-cp37m-manylinux1_x86_64.whl
  Processing /var/useDownloadCache/wheels/d9/45/dd/65f0b38450c47cf7e5312883deb97d065e030c5cca0a365030/PyYAML-5.1.2-cp37-cp37m-linux_x86_64.whl
  Collecting scipy
    Using cached https://files.pythonhosted.org/packages/94/7f/b535ec711cbcc3246abea4385d17e1b325d4c3404dd86f15fc4f3dba1dbb/scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl
  Collecting torch>=1.0.0
  
  
  STDERR: /bin/sh: line 1:     6 Killed                  python3.7 -m pip install -t /var/task/ -r /var/task/requirements.txt --cache-dir /var/useDownloadCache
  
      at filterCommands.forEach (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/serverless-python-requirements/lib/pip.js:320:13)
      at Array.forEach (<anonymous>)
      at installRequirements (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/serverless-python-requirements/lib/pip.js:307:28)
      at installRequirementsIfNeeded (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/serverless-python-requirements/lib/pip.js:532:3)
      at ServerlessPythonRequirements.installAllRequirements (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/serverless-python-requirements/lib/pip.js:611:29)
      at ServerlessPythonRequirements.tryCatcher (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/promise.js:673:18)
      at /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/bluebird/js/release/nodeback.js:42:21
      at fs.chmod.err (/private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/fs-extra/lib/copy/copy.js:120:12)
      at /private/var/folders/yl/c5z1v7897q3g9ywlj63pm0840000gn/T/bentoml-temp-xa4ebrj1/node_modules/graceful-fs/polyfills.js:243:20
      at /Users/HenryDashwood/bentoml/node_modules/graceful-fs/polyfills.js:243:20
      at FSReqWrap.args [as oncomplete] (fs.js:140:20)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.16.3
     Framework Version:         1.53.0
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0
 

Failed to create deployment facial-features-detector. INTERNAL:   Error: STDOUT: Collecting bentoml==0.4.8
```

**Comment by yubozhao** [comment] 2019-10-28 06:51
@HenryDashwood I see.  

Are you using the notebook that you mentioned in this issue post(https://github.com/HenryDashwood/facial-features-detector/blob/master/code/pytorch.ipynb)?  

If you are, I would love to use that and reproduce it and trying to fix on my local.  Last time I was trying with your notebook, I don't have the proper data in cell 3 `images_path = '../data/resized_images'
labels_path = '../data/resized_labels.csv'`.  I would love to use that notebook, or whichever notebook/code you could share to work on this issue.

I am out of my normal working environment for next few weeks, I might be slow to respond.  Sorry about that in advance.

**Comment by HenryDashwood** [comment] 2019-10-29 00:13
I feel a bit queasy passing the data around because it doesn't belong to me. What I have done though is make a new notebook [here](https://github.com/HenryDashwood/facial-features-detector/tree/master/regression_demo) based on a Fastai demo and which can be run on a laptop in 5-10 minutes. As you can see it hits the same issue. I did a pip freeze on my conda environment as well in case that's helpful.

**Comment by yubozhao** [comment] 2019-10-29 01:07
@HenryDashwood no worries. Totally understand. I will try out the new notebook you linked here. Thanks for taking your time to do that!  I will get back to you soon on it

**Comment by parano** [comment] 2019-11-18 18:44
@HenryDashwood @yubozhao  closing this issue now as it seem to be an issue with AWS serverless and PyTorch - feel free to reopen or open a new issue if you continue running into this.

Note that we are also moving away from serverless framework to AWS sam and native APIs, which should help us avoid the issues with NPM.

**Closed by parano** 2019-11-18 18:44 UTC
Labels: bug

**Comment by HenryDashwood** [comment] 2019-11-26 01:20
The thing is that I can't get Bentoml to run a later version of Serverless than 1.53. Even when I remove it manually and upgrade to the latest version. Is this a deliberate decision on your part?

**Comment by yubozhao** [comment] 2019-11-26 09:34
@HenryDashwood For the serverless based lambda deployment, yes we locked down the `serverless` version to 1.53.0, because the possible changes in the upstream CLI output might break existing code. 

We just release BentoML version `0.5.2`.  In this version, we use the official AWS serverless tool `SAM` for Lambda Deployment.  Now, you can customize more options for your deployment such as how much memory you want to have available for your function.  

We also customized the way saving and loading artifacts to work with Lambda's deployment size limitation.  The artifacts will be saved to S3 bucket, it won't take up your deployment bundle size.  

Give it a try, and let me know how it goes.  You can upgrade your bentoml version by using the command `pip install -U bentoml`

Cheers

**Comment by HenryDashwood** [comment] 2019-11-28 01:13
The new update looks really good and I can feel this getting closer! 

I am having a problem though getting my model on to Lambda. The deploy command has been hanging on the ```Packaging lambda project``` stage. You can see the output of my command at the bottom of the notebook [here](https://github.com/HenryDashwood/facial-features-detector/blob/master/code/train.ipynb). 

I don't think this is an issue specific to my Macbook or my internet connection because I've tried the same process on a remote instance and it gets stuck on the step. How long would you normally expect this stage to take? The longest I left one deployment was ~24 hours which I'm fairly sure is long enough!

**Comment by yubozhao** [comment] 2019-11-28 03:44
@HenryDashwood Thank you for the support!

The `SAM package` command is basically zip up the code in the built directory and upload to S3.  I don't expect it to take more than half hour, depends on how big is the zip and your upload speed. 

Since you are using fastai to do image detection, I will use fastai pet classification notebook, since they both use fastai.vision package for test, here is the notebook link: https://github.com/bentoml/gallery/blob/master/fast-ai/pet-image-classification/fast-ai-pet-image-classification.ipynb  I will get back to you with the results
