### ISSUE TITLE
Import tensorflow takes too much memory

### ISSUE THREAD

**Issue by chlee1016** [bentoml/BentoML#2861] opened 2022-08-04 18:53 UTC
### Describe the bug

`import tensorflow` takes too much memory for api server worker.
Please see the `RES` column.

Table 1. w/o import tensorflow
The memory takes about 85MB per api server worker.
```bash
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
     8 root      20   0 2169788  85528  13168 S   0.3   0.1   0:01.94 bentoml
     1 root      20   0    3968   1552   1288 S   0.0   0.0   0:00.00 bentoml_service
    68 root      20   0 2436204  84924  11472 S   0.0   0.1   0:01.41 python3
    69 root      20   0 2432652  84780  11424 S   0.0   0.1   0:01.54 python3
    70 root      20   0 2432652  84780  11424 S   0.0   0.1   0:01.30 python3
    71 root      20   0 2432660  84788  11424 S   0.0   0.1   0:01.78 python3
   296 root      20   0    4232   2232   1632 S   0.0   0.0   0:00.00 bash
   304 root      20   0    6092   1804   1296 R   0.0   0.0   0:00.00 top
```

Table 2. w/ import tensorflow
The memory takes about 870MB per api server worker.
```bash
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   305 root      20   0   24.1g 873112 250220 S   0.3   0.3   0:05.63 python3
   306 root      20   0   24.1g 871872 250216 S   0.3   0.3   0:05.78 python3
   308 root      20   0   24.1g 871744 250220 S   0.3   0.3   0:05.48 python3
     1 root      20   0    3968   1552   1288 S   0.0   0.0   0:00.02 bentoml_service
     7 root      20   0   23.3g 872388 251856 S   0.0   0.3   0:06.67 bentoml
   304 root      20   0   24.1g 871560 250160 S   0.0   0.3   0:05.34 python3
  1480 root      20   0    4232   2236   1636 S   0.0   0.0   0:00.02 bash
  1491 root      20   0    6096   1812   1296 R   0.0   0.0   0:00.01 top
```

I know that I can make the tensorflow model as a runner, but I want to run simple preprocessing logic after I/O that can be executed by api server worker.

### To reproduce

Implement simple api service and preprocessing logic using tf.
```python
# in service.py
import bentoml


# This is an example of preprocessor, for dummy inference using tf.
class Preprocessor():
    def __init__(self):
        import tensorflow as tf
        a = tf.constant(5)  
        b = tf.constant(2)
        self.c = tf.multiply(a, b)
        self.sess = tf.Session()

    def predict():
        self.sess.run(self.c)


preprocessor = Preprocessor()  # 
svc = bentoml.Service("my_service")


@svc.api(input=JSON(), output=JSON())
async def predict(req) -> Dict:
    async with aiohttp.ClientSession() as session:
        async with session.get('https://features/get', params=input_array[0]) as resp:
            features = get_features(await resp.text())
            preprocessor.predict(features)  #
            ...    

```

Run your service.
```bash
bentoml serve service.py:svc
```

After removing preprocessor from `service.py`, we get the result described in Table 1.

### Expected behavior

The memory should slightly increase for api server worker.

### Environment

bentoml: 1.0.2
python: 3.8

**Comment by aarnphm** [comment] 2022-08-05 01:02
Thanks for the mock. I will take a stab at it.

**Comment by parano** [comment] 2022-08-09 12:07
@chlee1016 I think in this case, it makes more sense to run this logic in the Runner process, you can actually add custom pre/post-processing logic to a model runner following this example: https://github.com/bentoml/BentoML/pull/2885

**Comment by aarnphm** [comment] 2022-08-10 08:52
From the quick look at your mock @chlee1016, I notice that you are creating a session lazily. I believe this is the root cause of tensorflow taking a lot of memory. Since `bentoml` spawns multiple `api_workers`, this means that multiple session will be spawned, which leads to increase in memory. 

I would suggest you try out Chaoyu recommendation.

Also a sidenote, since [`tf.Session`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session) is a deprecated for v2, You can try out something like:
```python
import contextlib

class Preprocessor:
    def __init__(self):
        import tensorflow as tf
        a = tf.constant(5)  
        b = tf.constant(2)
        self.session_stack = contextlib.ExitStack()
        self.session_stack.enter_context(tf.device(self.device_name))

    def preprocess(self):
        return tf.multiply(a, b)

    def __del__(self):
        try:
           self.session_stack.close()
        except RuntimeError:
            pass
```

**Comment by aarnphm** [comment] 2023-01-19 07:41
Hi there, any updates on this?

**Comment by frostming** [comment] 2024-07-11 01:14
Closing due to lack of activities

**Closed by frostming** 2024-07-11 01:14 UTC
Labels: bug
